// Code generated by "goki generate"; DO NOT EDIT.

package main

import (
	"goki.dev/gti"
	"goki.dev/ordmap"
)

var _ = gti.AddType(&gti.Type{
	Name:      "main.Graph",
	ShortName: "main.Graph",
	IDName:    "graph",
	Doc:       "Graph contains the lines and parameters of a graph",
	Directives: gti.Directives{
		&gti.Directive{Tool: "gti", Directive: "add", Args: []string{}},
	},
	Fields: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{
		{"Params", &gti.Field{Name: "Params", Type: "github.com/kkoreilly/marbles.Params", LocalType: "Params", Doc: "", Directives: gti.Directives{}, Tag: "view:\"-\" desc:\"the parameters for updating the marbles\""}},
		{"Lines", &gti.Field{Name: "Lines", Type: "github.com/kkoreilly/marbles.Lines", LocalType: "Lines", Doc: "", Directives: gti.Directives{}, Tag: "view:\"-\" desc:\"the lines of the graph -- can have any number\""}},
		{"Marbles", &gti.Field{Name: "Marbles", Type: "[]*github.com/kkoreilly/marbles.Marble", LocalType: "[]*Marble", Doc: "", Directives: gti.Directives{}, Tag: "view:\"-\" json:\"-\""}},
		{"State", &gti.Field{Name: "State", Type: "github.com/kkoreilly/marbles.State", LocalType: "State", Doc: "", Directives: gti.Directives{}, Tag: "view:\"-\" json:\"-\""}},
		{"Functions", &gti.Field{Name: "Functions", Type: "github.com/kkoreilly/marbles.Functions", LocalType: "Functions", Doc: "", Directives: gti.Directives{}, Tag: "view:\"-\" json:\"-\""}},
		{"Vectors", &gti.Field{Name: "Vectors", Type: "github.com/kkoreilly/marbles.Vectors", LocalType: "Vectors", Doc: "", Directives: gti.Directives{}, Tag: "view:\"-\" json:\"-\""}},
		{"Objects", &gti.Field{Name: "Objects", Type: "github.com/kkoreilly/marbles.Objects", LocalType: "Objects", Doc: "", Directives: gti.Directives{}, Tag: "view:\"-\" json:\"-\""}},
	}),
	Embeds: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}),
	Methods: ordmap.Make([]ordmap.KeyVal[string, *gti.Method]{
		{"Graph", &gti.Method{Name: "Graph", Doc: "Graph updates graph for current equations, and resets marbles too", Directives: gti.Directives{
			&gti.Directive{Tool: "gti", Directive: "add", Args: []string{}},
		}, Args: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}), Returns: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{})}},
		{"Run", &gti.Method{Name: "Run", Doc: "Run runs the marbles for NSteps", Directives: gti.Directives{
			&gti.Directive{Tool: "gti", Directive: "add", Args: []string{}},
		}, Args: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{}), Returns: ordmap.Make([]ordmap.KeyVal[string, *gti.Field]{})}},
	}),
})
